# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02446b3d847ee659725b630358999d3c95774e605259463847ad60399f04384d71d81eb2c4aeaf2300127ef2ccf60d39c9f2dfaae526d57e647eb148d21152d2

test:
  secret_key_base: 95ed84fa319bb96afb7bace1577bd2cee73797836f877a748a3d01ecfa4a1eb16b5bfd32703ca3fd366794ad66f646757cc537e5a9446895e6156408b94f3d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
